Add opitmized variant

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -4,51 +4,65 @@ on:
   workflow_dispatch:
   
 jobs:
-  build:
+  check:
     runs-on: ubuntu-latest
+    outputs:
+      ffmpeg_version: ${{ steps.check.outputs.ffmpeg_version }}
+      build_needed: ${{ steps.check.outputs.build_needed }}
     steps:
       - name: Checkout code
         uses: actions/checkout@v6
+
       - name: Check ffmpeg version
         run: |
           FFMPEG_VERSION=$(curl -s https://ffmpeg.org/releases/ | sed -nE 's/.*ffmpeg-([0-9.]+).tar.*/\1/p' | sort -V | tail -1)
-          echo "FFMPEG_VERSION=$FFMPEG_VERSION" >> $GITHUB_ENV
+          echo "ffmpeg_version=$FFMPEG_VERSION" >> $GITHUB_OUTPUT
           echo "Latest version is $FFMPEG_VERSION"
 
           REPO_RELEASE=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r .tag_name)
           echo "Latest repo release is $REPO_RELEASE"
 
           if [[ "$FFMPEG_VERSION" == *"$REPO_RELEASE"* ]]; then
-            echo "BUILD_NEEDED=0" >> "$GITHUB_ENV"
+            echo "build_needed=0" >> "$GITHUB_OUTPUT"
           else
-            echo "BUILD_NEEDED=1" >> "$GITHUB_ENV"
+            echo "build_needed=1" >> "$GITHUB_OUTPUT"
           fi
+  build:
+    needs: check
+    if: needs.check.outputs.build_needed == '1'
+    runs-on: ubuntu-latest
+    strategy:
+      fail-fast: true
+      matrix:
+        include:
+          - dockerfile: Dockerfile
+            variant: armel
+          - dockerfile: Dockerfile.optimized
+            variant: armel_optimized
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v6
       
       - name: Set up QEMU
-        if: ${{ env.BUILD_NEEDED == 1 }}
         uses: docker/setup-qemu-action@v4
         with:
           platforms: arm
           image: tonistiigi/binfmt:qemu-v8.1.5
           
       - name: Set up Docker Buildx
-        if: ${{ env.BUILD_NEEDED == 1 }}
         uses: docker/setup-buildx-action@v4
 
       - name: Build the package
-        if: ${{ env.BUILD_NEEDED == 1 }}
         run: |
-          docker buildx build --load --tag ffmpeg --platform linux/arm/v5 --allow security.insecure --no-cache --build-arg FFMPEG_VERSION="${{ env.FFMPEG_VERSION }}" .
+          docker buildx build --load --tag ffmpeg --platform linux/arm/v5 --allow security.insecure --no-cache --build-arg FFMPEG_VERSION="${{ needs.check.outputs.FFMPEG_VERSION }}" --file ${{ matrix.dockerfile }}
 
       - name: Extract the package
-        if: ${{ env.BUILD_NEEDED == 1 }}
         shell: bash
         run: |
           docker create --name ffmpeg ffmpeg
-          docker cp ffmpeg:./"ffmpeg_${{ env.FFMPEG_VERSION }}_armel.deb" "ffmpeg_${{ env.FFMPEG_VERSION }}_armel.deb" || echo "ffmpeg package not found"
+          docker cp ffmpeg:./"ffmpeg_${{ needs.check.outputs.FFMPEG_VERSION }}_${{ matrix.variant }}.deb" "ffmpeg_${{ needs.check.outputs.FFMPEG_VERSION }}_${{ matrix.variant }}.deb" || echo "ffmpeg package not found"
 
       - name: Upload ffmpeg as a new release
-        if: ${{ env.BUILD_NEEDED == 1 }}
         uses: svenstaro/upload-release-action@v2
         with:
           repo_token: ${{ secrets.REPO_TOKEN }}
